### ISSUE TITLE
Enormous file in AppBuilder CLI installation

### ISSUE THREAD

**Issue by tjvantoll** [Telerik-Verified-Plugins/Telerik-Analytics#1]
Hey all,

When I install the analytics plugin through the AppBuilder CLI (`appbuilder plugin fetch https://github.com/Telerik-Verified-Plugins/Telerik-Analytics`), I end up with a file that's 62MB, which seems wrong. The file is `plugins/com.telerik.plugin.telerikanalytics/lib/ios/libEQATECAnalyticsMonitoriOS.a`.

Thanks.

**Comment by ghost** [comment]
Hi TJ,
I know, it's crazy. But unfortunately it's not a mistake. The iOS monitor simply _is_ that big. It contains 5 libs (slices) for 32-bit and 64-bit arm and simulator (armv7, armv7s, arm64, i386, x86_64) and for some reason each lib is pretty big on iOS. In comparison, the Mac OS X monitor is just 3MB. I tried frantically to reduce the size years ago but without any luck. On the bright side, when linked into an app the monitor only adds few MB to the ipa.
cheers, Richard

**Comment by tjvantoll** [comment]
Hey Richard,

After I install the analytics plugin (`appbuilder plugin fetch https://github.com/Telerik-Verified-Plugins/Telerik-Analytics`) my AppBuilder iOS build times go up exponentially. I just timed an iOS build at 10 minutes, 21 seconds.

Even though the ipa might gain only a few MB, AppBuilder is clearly doing something during the build to slow things down enough to make this plugin unusable. Is there any way we can work around that? I guess I could use the [new _.debug._ syntax](http://docs.telerik.com/platform/appbuilder/build-configurations/overview), but even then it seems like I shouldn't have to wait 10 minutes to test my analytics code. At the very least we should document this somewhere.

Any ideas? cc @rdlauer for AppBuilder-related ideas

**Comment by rdlauer** [comment]
Wow, I'm not sure what could be causing this from the AppBuilder build side. cc'ing @ligaz who may have a better idea.

**Comment by ghost** [comment]
That's certainly not expected. I haven't tried what you're doing now, but when I tested the plugin in AppBuilder last year (both as an imported plugin before it was included into AppBuilder as a built-in plugin that could just be enabled, and also afterwards as a built-in plugin) I didn't really notice any increase in build-time. So something's definitely wrong here. Maybe a tool chain step that has never handled such a large binary component before but has worked fine with smaller parts.

**Comment by ligaz** [comment]
Hey @tjvantoll,

It seems you are installing the plugin as a custom plugin. Do you have an `.abignore` file in your project?
Also regarding the marketplace plugins in the CLI it is preferred to use the `add` command:

``` bash
$ appbuilder plugin add "Telerik Analytics"
```

which will just add metadata to the `.abproject` about the plugin you have installed, similarly to the way Core plugins are handled.

**Comment by tjvantoll** [comment]
Hi @ligaz,

My project does have a `.abignore`, but it's the [default one that AppBuilder generates](https://github.com/tjvantoll/city-search-challenge/blob/master/app/.abignore).

Installing the plugin via `appbuilder plugin add "Telerik Analytics"` dropped the build time back to what I would expect. (Although I did get an unrelated error message about Streethawk, see the third line below.)

```
$ appbuilder plugin add "Telerik Analytics"
Gathering information for plugins...
Unable to fetch data for Streethawk plugin. Please, try again in a few minutes.
Plugin Telerik Analytics was successfully added.
```

I used `fetch` command because that's what the [analytics plugin's page](http://plugins.telerik.com/plugin/telerik-analytics) says to do (under “Install plugin using AppBuilder CLI”). We should probably update that. cc @rdlauer 

Thanks guys.

**Comment by rdlauer** [comment]
@ligaz yes we need to update all of these instructions on the marketplace site. What is the format of the command? Is what is in quotes always the title of the plugin as displayed on plugins.telerik.com?

**Comment by ligaz** [comment]
@rdlauer Yes we should do this as this supported landed in CLI as of v2.7. The format is `plugin add` and then the plugin name (the same way it works for Core or Integrated plugins). We are going to add support for plugin id as well but this will be available in v2.8. 

Regarding the Streethawk plugin it seems that it is not properly configured. I have checked it on the plugins site and its repo is pointing to bitbucket (should be github so we can query for tags). Also it is not available in the Telerik-Verified-Plugins org and does not have a sample app. @EddyVerbruggen can you check this.

**Comment by rdlauer** [comment]
@ligaz @EddyVerbruggen I'll talk to the Streethawk guys (this was our first third party submission). But first, what are our minimum requirements for compatibility? Do we need the plugin to be in GitHub? Does it have to be in our org? We know they don't have a sample app.

I'll also spend some time today updating the CLI instructions.

**Comment by ligaz** [comment]
> Do we need the plugin to be in GitHub? 

Yes, because we are using the GitHub API to fetch all tags for a given plugin and display those as applicable versions for the plugin.

> Does it have to be in our org?

No, as long as it is in GitHub it will be fine. My point for our org was that it is becoming a hub for such plugins. Having it in our org also gives us flexibility to fix something if it is not working or add new versions (tags) when the author does not do it on her own.

> We know they don't have a sample app. 

I thought that one of the requirements to be `verified` was to have a working sample with the plugin. Maybe we can relax that but still I think it will be good to have one.

**Comment by rdlauer** [comment]
FYI, all of the plugins in the marketplace have their CLI instructions updated now.

**Comment by tjvantoll** [comment]
@rdlauer I was doing a little playing around this morning and by chance hit this:

$ appbuilder plugin add "Telerik Push Notifications"
Gathering information for plugins...
Invalid plugin name: Telerik Push Notifications

:(

**Comment by EddyVerbruggen** [comment]
Hi @tjvantoll according to the `appbuilder plugin add --available` command that one is called `PushPlugin`. Note that this plugin will soon me updated to handle iOS8 interactive notifications.

**Comment by rdlauer** [comment]
I just went through and updated about 1/3 of the plugins to match up the names with the name given in `appbuilder plugin add --available`. Should be good from here on out.

**Comment by tjvantoll** [comment]
I think all the items in here have been resolved so I'm going to go ahead and close this. Thanks again everyone.
