### ISSUE TITLE
Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by tjvantoll** [Telerik-Verified-Plugins/Telerik-Analytics#2]
I updated my iOS app to include this plugin and I received the following email from Apple:

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "City Search―A Geography Challenge". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
> 
> Regards,
> 
> The App Store team

I did not receive this warning from previous iOS submissions, and the only plugin I added for this submission was the Telerik Analytics one, so I suspect (although I can't say I'm positive by any means) that the warning is because of this plugin. As the email said this is just a warning, but it's still a bit of a nuisance. 

So I'm wondering, does this plugin use the push APIs?

Thanks.

**Comment by ligaz** [comment]
Hey TJ,

This is a general issue with Cordova that was introduced in the 3.5 time-frame. You can read more about it [here](http://community.phonegap.com/nitobi/topics/pgb_3_5_missing_push_notification_entitlement).

We are considering pushing a _fix_ to the Cordova codebase in order to prevent this warning from showing, but we will need some time to get it right.

**Comment by tjvantoll** [comment]
Thanks @ligaz. Odd that I didn't get this on my initial submission because that was also using Cordova 3.5. Since this doesn't seem to be related to analytics I'll close this.

Thanks guys.
